### PR TITLE
IGAPP-937: Add support for ukrainian

### PR DESCRIPTION
**Pull request by klinzo**
This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

### CODE REVIEW

**Comment by klinzo** [comment]
Testable here: https://integreat.app/testumgebung/uk (production cms)

**Review by Taggotty — COMMENTED** [review]
for me the page is rendered empty when navigating to https://integreat.app/testumgebung/uk . Both on chrome and firefox

**Comment by klinzo** [comment]
> for me the page is rendered empty when navigating to https://integreat.app/testumgebung/uk . Both on chrome and firefox

I mean obviously you need to use localhost

**Review by SteffiStuffel — APPROVED** [review]
Tested with special ukrainian letters, works fine.

**Pull request merged**
