### PR TITLE
IGAPP-636: Refactor pois and navigation

### PR DESCRIPTION
**Pull request by steffenkleinle**
This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

### CODE REVIEW

**Review by sarahsporck — APPROVED** [review]
Works fine :)

**Review by LeandraH — APPROVED** [review]
Looks good, tested in Firefox, simulated Android, and simulated iOS. Still getting the error we talked about in simulated iOS when switching language or city, I'll have to get my setup with a real iOS device running at some point to test that...
image

**Comment by steffenkleinle** [comment]
> Looks good, tested in Firefox, simulated Android, and simulated iOS. Still getting the error we talked about in simulated iOS when switching language or city, I'll have to get my setup with a real iOS device running at some point to test that... 

Good thing you mention this again, I may know what the problem is! Will look into it :) Do you perhaps have a little more information when exactly this occurs? Directly after switching language? Perhaps you have a screen recording?

**Comment by LeandraH** [comment]
I made a screen recording, it's right after clicking on the new location / language.

https://user-images.githubusercontent.com/18513943/203379159-1cfb1360-2b5e-4a5a-a338-e1925226e6eb.mp4

**Pull request merged**
