### PR TITLE
2699: Support appointment booking offer

### PR DESCRIPTION
**Pull request by steffenkleinle**
### Short description

Add support for appointment booking and other external embedded offers on the first level.

### Proposed changes

- Add and use helper to map categories to `TileModel`s which handles external embedded offers 
- Merge and move TileModel to shared
- Add support for external urls in the `Tile` component (native)

### Side effects

- Non-internal *embedded* offers are now all treated as external offers
- Content/children of categories with embedded external offers are not displayed anymore

### Resolved issues

Fixes: #2699.

---

### CODE REVIEW

**Review by LeandraH — APPROVED** [review]
Very cool! Tested in Firefox and emulated iOS

**Review by ztefanie — CHANGES_REQUESTED** [review]
Tested on Chrome, going to the offers tab (http://localhost:9000/testumgebung/de/offers) throws an error now.

**Comment by steffenkleinle** [comment]
> Tested on Chrome, going to the offers tab (http://localhost:9000/testumgebung/de/offers) throws an error now.

Good catch. Filtering out the offer now, should be fixed.

**Review by ztefanie — APPROVED** [review]
hmh now there for malte the offers tab is shown but empty, but I think we preivously had this problem, too, so I will approve.

**Comment by steffenkleinle** [comment]
> hmh now there for malte the offers tab is shown but empty, but I think we preivously had this problem, too, so I will approve.

Should be removed soon anyway so I think this is okay for now.

**Pull request merged**
