### PR TITLE
2948: Start a new chat for each region

### PR DESCRIPTION
**Pull request by steffenkleinle**
### Short description

Start a new chat for each region instead of sharing the chat instance.
This would break the chat in the backend.

### Proposed changes

Store the id of the chat in the local storage related to the city.

### Side effects

:warning: Previous chats won't work anymore (unless the chat id is copied manually to the new local storage entry).

### Testing

Open the chat in testumgebung and send a message.
Then go to muenchen and open the chat and confirm that there is no chat yet.

### Resolved issues

Fixes: #2948, https://github.com/digitalfabrik/integreat-chat/issues/54.

---

### CODE REVIEW

**Comment by steffenkleinle** [comment]
⚠️ @svenseeberg  Previous chats won't work anymore (except the chat id is copied manually to the new local storage entry).

**Review by LeandraH — APPROVED** [review]
Nice, tested in Firefox

**Review by ztefanie — APPROVED** [review]
Tested on firefox and chrome :+1:

**Comment by svenseeberg** [comment]
> Previous chats won't work anymore after this PR is released to production

This is totally fine. We are currently in an alpha stage and breaking changes are totally acceptable.

**Pull request merged**
