### PR TITLE
2397: Update macos resource class

### LINKED ISSUE #2397: [CI] Update macos resource classes
**Is your feature request related to a problem? Please describe.**
We are still using deprecated circle ci resource classes like `macos.x86.medium.gen2` or `medium`
This will result in failed tests at the end of the year

**Describe the solution you'd like**
Replace old macos resource classes by the new classes.
More information you can find here:
https://discuss.circleci.com/t/macos-intel-support-deprecation-in-january-2024/48718?utm_source=test&utm_medium=test&utm_campaign=test&mkt_tok=NDg1LVpNSC02MjYAAAGNzIE9Pez3OWH2fkycbcPms-t96qglk36p49VbsHFasI0_2yE1mXekDmmLFP9PgVWPTkruWL1PnMe5rrRIb2NbqWUks1gwNnLM27Or_OeSVILi3A

### PR DESCRIPTION
**Pull request by f1sh1918**
### Short description

Switch from old deprecated x86 to m1 resource class because tests will fail in the end of the year

### Proposed changes

Switch resource classes for ios builds if deprecated resource are in use

resolves #2397

### CODE REVIEW

**Review by steffenkleinle — APPROVED** [review]
Should we update those for lunes as well?

**Comment by f1sh1918** [comment]
> Should we update those for lunes as well?

there is already a pr

**Review by sarahsporck — APPROVED** [review]
Apparently this also speeds up the build time by about 25% -> https://circleci.com/blog/m1-mac-resource-class/?utm_medium=PR&utm_source=business-wire&utm_campaign=m1

But small disclaimer. It also costs twice as many credits https://circleci.com/product/features/resource-classes/#macos

**Comment by sarahsporck** [comment]
@f1sh1918 would you mind triggering the build_ios job for this pr? Mostly to test that the ci is working.

**Comment by f1sh1918** [comment]
> > > @f1sh1918 would you mind triggering the build_ios job for this pr? Mostly to test that the ci is working.
> > 
> > 
> > @sarahsporck no idea how i can trigger a job for this particular branch
> 
> You can replace the branch name (from `main` to `2397-update-macos-resouce-class`) in the `trigger-pipeline` script and run it:
> 
> > yarn trigger-pipeline trigger e2e_tests --api-token <your-api-token>

@steffenkleinle yes but this workflow isn't using the `build_ios` job with the new ressource i would have to adjust the circle ci config temporary?! Or how should i test this job? It's only including in delivery workflows

**Comment by steffenkleinle** [comment]
> > > > @f1sh1918 would you mind triggering the build_ios job for this pr? Mostly to test that the ci is working.
> > > 
> > > 
> > > @sarahsporck no idea how i can trigger a job for this particular branch
> > 
> > 
> > You can replace the branch name (from `main` to `2397-update-macos-resouce-class`) in the `trigger-pipeline` script and run it:
> > > yarn trigger-pipeline trigger e2e_tests --api-token
> 
> @steffenkleinle yes but this workflow isn't using the `build_ios` job with the new ressource i would have to adjust the circle ci config temporary?! Or how should i test this job? It's only included in delivery workflows

If you are running this on this branch your changes are included (also build_ios with new resource class). Otherwise just merge it and it will be tested on monday 😀

**Pull request merged**
