### PR TITLE
IGAPP-1061: Upgrade RN to 0.70 on iOS

### PR DESCRIPTION
**Pull request by LeandraH**
This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

### CODE REVIEW

**Review by SteffiStuffel — APPROVED** [review]
Looks valid. Not tested.

**Review by f1sh1918 — APPROVED** [review]
Tested on simulator. Works nice

atm i can't deploy on real device since i have to update XCode which takes time.
Did you test on real device? At least push notifications should be tested before merging!

**Comment by sarahsporck** [comment]
Also the ci seems to dislike sth. I'll try to fix it on android in the other branch and hopefully this will also resolve the issue on ios

**Comment by LeandraH** [comment]
Yes, don't worry, I tested it on my phone, and just tested the push notification specifically again.

**Pull request merged**
