### PR TITLE
IGAPP-971: Titles that are to long are not devided by new line

### PR DESCRIPTION
**Pull request by f1sh1918**
This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

Test scenario:

1. Go to Testumgebung --> Bilder --> Scroll to "HierstehteinebesonderslangeÜberschrift"
2. Headline now should be broken into multiple lines
3. It breaks with the same behavior as in web (just to check same behavior) https://webnext.integreat.app/testumgebung/de/bilder

### CODE REVIEW

**Review by klinzo — APPROVED** [review]
Tested on android

**Review by SteffiStuffel — APPROVED** [review]
Tested. `&8203;` is not working, but not sure if this was the plan. I guess not.

**Comment by klinzo** [comment]
> Tested. `&8203;` is not working, but not sure if this was the plan. I guess not.

It was not because only the corresponding html tag would work and we don't want cities to directly work with html tags, see https://chat.tuerantuer.org/digitalfabrik/pl/oc8usf59ft8nbpqsrfrqrfnanr

**Comment by f1sh1918** [comment]
> Tested. `&8203;` is not working, but not sure if this was the plan. I guess not.

no this was not the issue in this ticket

**Pull request merged**
