### PR TITLE
2498 and 2499: Reduce execution time and reduce bundle size

### PR DESCRIPTION
**Pull request by steffenkleinle**
### Short description

A few optimizations to reduce execution time and reduce bundle size, mostly taken from #2705.

### Proposed changes

- Remove lodash in web, shared and translations
- Set `sideEffects: false` (see https://webpack.js.org/guides/tree-shaking/)
- Remove splash screen

### Side effects

There is no more splash screen on web (only visible with really slow internet).

### Resolved issues

Partly fixes: #2498, #2499.

---

### CODE REVIEW

**Review by LeandraH — COMMENTED** [review]
❓ Does /tools have side effects?

❓ This looks great but when I check the stat sizes in the bundle analyzer, I get a smaller size for main.blabla.js (from 2.86 MB down to 2.28 MB!) but the overall size stays exactly at 5.58 MB. Any ideas?

Otherwise it looks great, and I think it's definitely a good idea to especially remove Lodash but I'm a little confused about the sizing.

**Review by f1sh1918 — APPROVED** [review]
I already told sarah that i don't think we should put more effort into this, so not sure what was your motivation here. Did you find any improvements according execution time and bundle size @steffenkleinle ?
I checked the bundle sizes and the execution time as i also did in sarahs pr and i didn't find any significant improvements tbh.

If we really want a significant performance boost we might have to switch to NextJS.
All we do here is just "A drop in the ocean" in my opinion

I'm gonna approve this pr because removing lodash is a good choice and everything works fine but i think we should put effort into other topics or really switch to NextJS.

**Comment by steffenkleinle** [comment]
> ❓ Does /tools have side effects?

It should not have. Why?

> ❓ This looks great but when I check the stat sizes in the bundle analyzer, I get a smaller size for main.blabla.js (from 2.86 MB down to 2.28 MB!) but the overall size stays exactly at 5.58 MB. Any ideas?

I'll check.

**Comment by steffenkleinle** [comment]
> I already told sarah that i don't think we should put more effort into this, so not sure what was your motivation here. Did you find any improvements according execution time and bundle size @steffenkleinle ? I checked the bundle sizes and the execution time as i also did in sarahs pr and i didn't find any significant improvements tbh.
> 
> If we really want a significant performance boost we might have to switch to NextJS. All we do here is just "A drop in the ocean" in my opinion
> 
> I'm gonna approve this pr because removing lodash is a good choice and everything works fine but i think we should put effort into other topics or really switch to NextJS.

Agreed that this is only a drop in the ocean and for real performance improvements we have to look at SSR (for example with NextJS). Remix (https://remix.run/) might also be an option as in the next release it will be merged with react-router which we are already using (https://remix.run/blog/merging-remix-and-react-router), so migrating could be a lot less effort.

However, I think that removing lodash still makes sense. Since all the work (for web) was basically already done, I figured it makes sense to extract these changes and merge them nevertheless (even though the performance benefits are small or even non-existent). If you don't think we should merge this, please say.

**Comment by LeandraH** [comment]
> > ❓ Does /tools have side effects?
> 
> It should not have. Why?

I think you could add the `sideEffects: false` to that `package.json` too, then

**Comment by steffenkleinle** [comment]
> > > ❓ Does /tools have side effects?
> > 
> > 
> > It should not have. Why?
> 
> I think you could add the `sideEffects: false` to that `package.json` too, then

Probably won't make any difference as the tools package is not part of the monorepo setup. Won't hurt either though.

**Review by ztefanie — APPROVED** [review]
Not tested, code looks good. I agree with all of you, not a big win here, but also a good step to remove lodash.

**Comment by steffenkleinle** [comment]
Okay, I figured out why lodash is still included in the bundle: `loadTranslations` used `merge`. Therefore I replaced it with `deepmerge-ts` as well. I used https://statoscope.tech for deeper insights in the bundle size.
You can create a `stats.json` file using `yarn build bundle_analyzer` (put in `web/reports/bundle/stats.json`) which can then be uploaded there.

This PR reduces the size of the main chunk/entry point from 1.37 mb to 1.10 mb (raw from 2.9 mb to 1.8 mb), so hopefully we'll see some (little) improvement here...

**Comment by steffenkleinle** [comment]
@f1sh1918 what did you use to check for improvements?

**Comment by LeandraH** [comment]
Looks like quite a few methods from lodash are also used in `translations/tools/manage.ts`, not sure how those are running at the moment 😅

**Comment by steffenkleinle** [comment]
> Looks like quite a few methods from lodash are also used in `translations/tools/manage.ts`, not sure how those are running at the moment 😅

Those are not run at all in web/native, its only utility methods used to manage the translations. If you have a look at the bundle, lodash should not be included. If you think we should ditch altogether from our whole codebase, please open an issue.

**Review by LeandraH — APPROVED** [review]
Very nice, I now see a static size of 5.06 MB with main...js being 1.76 MB. Very cool, thank you!

**Pull request merged**
