### PR TITLE
IGAPP-1279: Fix Symmetry

### PR DESCRIPTION
**Pull request by SteffiStuffel**
This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

### CODE REVIEW

**Review by LeandraH — APPROVED** [review]
Thanks for the quick fix, tested in Firefox

**Review by sarahsporck — APPROVED** [review]
Tested in Safari ✅

**Review by f1sh1918 — COMMENTED** [review]
really strange looks like styled components can not use this `screen and` syntax which is in general valid css syntax. Please also remove the other `screen and` occurrences which also lead to errors. thx for the quick fixing

**Review by f1sh1918 — APPROVED** [review]

**Review by f1sh1918 — COMMENTED** [review]
@SteffiStuffel oh dear i found the issue
`dimension.ts`

`minMaxWidth: 'screen and (min-width: 1101px)',` -> we should not add here `screen and` because we may want to use a different media type for some cases with this dimension and its error prone if it differs from other dimensions.
After removing that the valid css syntax is working and you can revert you change

**Comment by LeandraH** [comment]
Good catch, thanks for fixing!

**Pull request merged**
