### PR TITLE
2621: POIs information overflows beyond the container

### PR DESCRIPTION
**Pull request by Njivaniaina2407**
### Short description

When the URL of the website for certain POIs is lengthy, it causes the text to overflow beyond the container boundaries.
The URL should fit within the container.

### Proposed changes

Make the link go to the line if it's too long

### Resolved issues

Fixes: #2621

---

### CODE REVIEW

**Review by LeandraH — APPROVED** [review]
Very nice, tested on Safari :)

**Review by steffenkleinle — COMMENTED** [review]
Works as expected. However, I could also not reproduce this on current webnext/beta/production. Am I missing something?

**Comment by Njivaniaina2407** [comment]
The overflow is also reproduced here: 
https://webnext.integreat.app/muenchen/en/locations/stadtjugendamt
Or are you talking about another link?
@steffenkleinle

**Comment by steffenkleinle** [comment]
> The overflow is also reproduced here: https://webnext.integreat.app/muenchen/en/locations/stadtjugendamt Or are you talking about another link? @steffenkleinle

Oh okay, on firefox it works fine but on chromium it overflows as described and is fixed by your PR, so well done!

**Review by steffenkleinle — APPROVED** [review]

**Pull request merged**
