### PR TITLE
IGAPP-636: Refactor landing

### PR DESCRIPTION
**Pull request by steffenkleinle**
This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

### CODE REVIEW

**Review by sarahsporck — COMMENTED** [review]
Good work!

The EasterEggImage throws an error: `[Error: Failed to delete '/data/user/0/app.integreat.test/files']`

**Comment by steffenkleinle** [comment]
> Good work!
> 
> The EasterEggImage throws an error: `[Error: Failed to delete '/data/user/0/app.integreat.test/files']`

Should be fixed now, could you please test again? Not sure what caused it in the first place though. Looks not that nice when switching the cms url since the list takes a while to load but since this is only a dev tool I think that should be fine.

**Review by LeandraH — APPROVED** [review]
Looks good, tested on iOS simulator

**Comment by steffenkleinle** [comment]
@sarahsporck ping

**Pull request merged**
