### PR TITLE
2897: Refresh cities every day

### PR DESCRIPTION
**Pull request by steffenkleinle**
### Short description

At the moment, cities are not refreshed at all anymore if a city has been selected.
In Landing, we call the refresh manually as a workaround.
However, if a city is selected, Landing is not rendered anymore and therefore the workaround is not triggered.

This PR works around that by using `useLoadWithCache` instead of `useLoadCities` in the `useCityContent` hook.

### Proposed changes

Use `useLoadWithCache` over `useLoadCities` in the `useCityContent` hook.

### Side effects

None.

### Testing

Instead of manually changing values in the CMS and waiting for the next day for the refresh to happen, you can also do the following:
- Change any property in `mapCityJson`, e.g. the following line to
https://github.com/digitalfabrik/integreat-app/blob/4529e219cb0c8ea866dff6348e1ce8b318b22b8c/shared/api/mapping/mapCityJson.ts#L29

``` ts
eventsEnabled: true
```
- Change the refresh condition in `useLoadWithCache`, i.e. the following line to
https://github.com/digitalfabrik/integreat-app/blob/4529e219cb0c8ea866dff6348e1ce8b318b22b8c/native/src/hooks/useLoadWithCache.ts#L41

``` ts
const shouldUpdate = forceUpdate || !lastUpdate || lastUpdate < DateTime.utc().startOf('day').plus({ day: 1 })
```

### Resolved issues

Fixes: #2897.

---

### CODE REVIEW

**Review by LeandraH — COMMENTED** [review]
Hmmm, I deactivated events in the CMS and set `shouldUpdate = true` in `useLoadWithCache`; I then tapped around in the app a little, in the hopes that that would trigger a refresh but only an actual pull-to-refresh did. Any ideas?


https://github.com/user-attachments/assets/1ef5a334-09c1-4ba4-9f2c-f6ef18eb8062

**Review by LeandraH — APPROVED** [review]
But it does work when the app is restarted (i.e. removed from the RAM and opened again), which seems to be the case that didn't work here :)

**Comment by f1sh1918** [comment]
@steffenkleinle 
i'm really not sure how to test what and what is expected. I did the changes you proposed to do.
Then i cleaned app from ram and restarted. I don't have any change.
If i set `eventEnabled: false` i expected that events will disappear.
But that only worked after i switched city.

**Review by ztefanie — APPROVED** [review]
Tested on android, works as expected :+1:

**Pull request merged**
