### PR TITLE
IGAPP-1011: Bed filter for shelter returns duplicated results

### PR DESCRIPTION
**Pull request by steffenkleinle**
This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

### CODE REVIEW

**Review by f1sh1918 — APPROVED** [review]
Even i can reproduce the console warning with children with duplicated key, its not shown duplicated in the list anymore. So really nice work. I was quite sure i tried the same solution before once but maybe i was confused because the console warning still existed and didn't check for the particular entries in the list

```js
Warning: Encountered two children with the same key, `1155`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

**Comment by steffenkleinle** [comment]
> Even i can reproduce the console warning with children with duplicated key, its not shown duplicated in the list anymore. So really nice work. I was quite sure i tried the same solution before once but maybe i was confused because the console warning still existed and didn't check for the particular entries in the list

The warning is still shown? That's odd, will look into it.

**Review by SteffiStuffel — APPROVED** [review]
Please delete branch IGAPP-1011-bed-filter-for-shelter-returns-duplicated-results   


Tested, works fine. Don't get a warning.

**Comment by steffenkleinle** [comment]
> Even i can reproduce the console warning with children with duplicated key, its not shown duplicated in the list anymore. So really nice work. I was quite sure i tried the same solution before once but maybe i was confused because the console warning still existed and didn't check for the particular entries in the list
> 
> ```js
> Warning: Encountered two children with the same key, `1155`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
> ```

Cannot reproduce, no warnings for me either. Perhaps you didn't clear the console?

**Pull request merged**
