### PR TITLE
2767: Fix cut off texts

### PR DESCRIPTION
**Pull request by ztefanie**
### Short description
Fix the text cut off

### Resolved issues

Fixes: #2767 

---

### CODE REVIEW

**Review by f1sh1918 — COMMENTED** [review]
It doesn't fix the issue for me on ios. I think it may be related to the `CategoryThumbnail` in `CategoryListItem`

image

**Comment by f1sh1918** [comment]
@ztefanie i added here a proposal how to fix the cut-off for both OS
https://github.com/digitalfabrik/integreat-app/pull/2771

**Comment by steffenkleinle** [comment]
> It doesn't fix the issue for me on ios. I think it may be related to the `CategoryThumbnail` in `CategoryListItem`

This is not an iOS specific issue, not working on Android with slightly longer titles as well. I opened #2774 instead.

**Comment by steffenkleinle** [comment]
Already done in #2774.

**Pull request closed without merging**
