### PR TITLE
IGAPP-931: Fix layout of aside when language change is opened

### PR DESCRIPTION
**Pull request by SteffiStuffel**
This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

### CODE REVIEW

**Comment by klinzo** [comment]
If @f1sh1918 didn't find another solution I think we should remove the sticky positioning.

**Comment by SteffiStuffel** [comment]
Also we can make the margin-top bigger, so it is enough for expanded language menu.

**Comment by klinzo** [comment]
> Also we can make the margin-top bigger, so it is enough for expanded language menu.

That sounds like a good solution!

**Review by klinzo — APPROVED** [review]
Good idea :+1: Tested on firefox

**Review by f1sh1918 — APPROVED** [review]

**Pull request merged**
