### PR TITLE
IGAPP-1332: Remove js-md5 and replace with md5

### PR DESCRIPTION
**Pull request by steffenkleinle**
This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

### CODE REVIEW

**Review by sarahsporck — COMMENTED** [review]
Any guidelines on how to test this? :)

**Comment by steffenkleinle** [comment]
> Any guidelines on how to test this? :)

You can do a production build in web and then search for `eval("require('crypto')")` and if you don't find anything we should be good.

**Review by sarahsporck — APPROVED** [review]
so when looking at the yarn.lock the `crypto` library should not be bundled.

**Review by LeandraH — APPROVED** [review]
Looks reasonable, and I didn't get any errors in Firefox or emulated iOS :)

**Pull request merged**
