### PR TITLE
2751: Fix pull to refresh for maps

### PR DESCRIPTION
**Pull request by steffenkleinle**
### Short description

Fix pull to refresh for maps.

### Proposed changes

- Fix pull to refresh for maps in full screen bottom action sheet
- Only render RefreshControl if a refresh function is passed

### Side effects

No pull to refresh is possible anymore if no refresh function is passed.

### Resolved issues

Fixes: #2751.

---

### CODE REVIEW

**Review by LeandraH — COMMENTED** [review]
I can't refresh on my iPhone on the maps page. If I pull the BottomActionSheet all the way to the top of the page, and then pull down anywhere, I just lower the BottomActionSheet again.

**Comment by steffenkleinle** [comment]
> I can't refresh on my iPhone on the maps page. If I pull the BottomActionSheet all the way to the top of the page, and then pull down anywhere, I just lower the BottomActionSheet again.

Does it work on android for you? Maybe you are pulling down from too much in the top?

**Comment by LeandraH** [comment]
> > I can't refresh on my iPhone on the maps page. If I pull the BottomActionSheet all the way to the top of the page, and then pull down anywhere, I just lower the BottomActionSheet again.
> 
> Does it work on android for you? Maybe you are pulling down from too much in the top?

Interestingly, it doesn't work on Android either, though that's just the emulator. I click pretty exactly where Svenja tapped in her video (just under the top of the BottomActionSheet) and pull, and it just does nothing. If I do the same thing on my real iPhone, I close the BottomActionSheet 🤷

**Comment by steffenkleinle** [comment]
> > > I can't refresh on my iPhone on the maps page. If I pull the BottomActionSheet all the way to the top of the page, and then pull down anywhere, I just lower the BottomActionSheet again.
> > 
> > 
> > Does it work on android for you? Maybe you are pulling down from too much in the top?
> 
> Interestingly, it doesn't work on Android either, though that's just the emulator. I click pretty exactly where Svenja tapped in her video (just under the top of the BottomActionSheet) and pull, and it just does nothing. If I do the same thing on my real iPhone, I close the BottomActionSheet 🤷

@f1sh1918 @ztefanie can you please test this as well? I had the same issue as @LeandraH at some point but its now all working for me. I thought its just because of starting the gesture in a slightly different place.

**Review by f1sh1918 — APPROVED** [review]
works for me on android real device. Can't check  ios real device. It's also okay for me if it doesn't work in bottom action sheet. 
Good work 👍

**Review by LeandraH — APPROVED** [review]
The bug was reported in Android, the behaviour there has been fixed. Thanks for working your way through this :)

**Pull request merged**
