### PR TITLE
IGAPP-1223: Fix testumgebung

### PR DESCRIPTION
**Pull request by SteffiStuffel**
This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

As deleting the cache worked for my real devices, I guess this PR fixes the issue, but I am not really sure, as I do not get this error on the emulator, but there was a warning and an error in the console, which disappeared with these changes. Hopefully someone of you has a good idea how to test this, otherwise we have to try.

### CODE REVIEW

**Comment by f1sh1918** [comment]
> This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/). You can find it there by looking for an issue with the key which is mentioned in the title of this pull request. It starts with the keyword **IGAPP**.
> 
> As deleting the cache worked for my real devices, I guess this PR fixes the issue, but I am not really sure, as I do not get this error on the emulator, but there was a warning and an error in the console, which disappeared with these changes. Hopefully someone of you has a good idea how to test this, otherwise we have to try.

@SteffiStuffel 
I think this issue is related to saving metaData with the same location name like "testumgebung" for test-cms if you have already saved data for the "testumgebung" in production cms.
I'm facing this error `'cannot store last update for unused city'` but i cannot reproduce Leandra's issue, so not 100% sure if there is a relation. Even the bug report is not helping tbh, so maybe a clear bug report could help reproducing the error.

Would be good if leandra can test it, because it can not reproduce and i'm not sure if we should merge it without more investigation. Even because i think it only happens if you switch cms and won't happen for users

**Comment by SteffiStuffel** [comment]
Will add better cache-naming for test-cms and prod-cms cities and reopen this, when I am finished

**Comment by LeandraH** [comment]
It's unfortunately not fixed with this. I attached a video but I'm not sure how helpful that is either. In the console, I'm getting a warning `Sending `progress` with no listeners registered.`

https://user-images.githubusercontent.com/18513943/217550369-a409ff74-4348-4808-95ca-8f04aa52c22a.mp4

**Comment by f1sh1918** [comment]
created new pr with proper branch naming

**Pull request closed without merging**
