### PR TITLE
2580: Center search icon

### PR DESCRIPTION
**Pull request by Njivaniaina2407**
Short description
The Search Icon is not centered with the input "Suche"

Proposed changes
Center and align the Search Icon with the input, set it a little lower

Side effects
Resolved issues
The Search Icon is aligned with the Input "Suche"

Fixes: https://github.com/digitalfabrik/integreat-app/issues/2580

---

### CODE REVIEW

**Review by LeandraH — COMMENTED** [review]
That solves the issue here very nicely, thank you! But I think we can make the code more future-proof by setting the parent display to flex and aligning its items with the center. That would also keep us safe in case we e.g. change the icon sizing at some point.

**Comment by f1sh1918** [comment]
> That solves the issue here very nicely, thank you! But I think we can make the code more future-proof by setting the parent display to flex and aligning its items with the center. That would also keep us safe in case we e.g. change the icon sizing at some point.

sorry i probably should have mentioned it again in the ticket here. This task was about learning sth. about flexbox :)

**Review by f1sh1918 — COMMENTED** [review]
Good Work :) Added a comment about `inline-flex`

**Review by LeandraH — APPROVED** [review]
Nicely done!

**Review by f1sh1918 — APPROVED** [review]

**Pull request merged**
