### PR TITLE
IGAPP-1032: Add finnish language

### PR DESCRIPTION
**Pull request by SteffiStuffel**
This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

### CODE REVIEW

**Review by f1sh1918 — COMMENTED** [review]
How can i test it?

**Comment by FritjofK** [comment]
I hope, I did it the right way. I was not sure whether it was needed in Testumgebung or Testumgebung Ende-zu-Ende, so I just created a few pages in both. 
There should be 4 pages in Finnish: 
Willkomen
-Beratung und Hillfe
--Test Inhalte
--Helferkreis

**Comment by SteffiStuffel** [comment]
> I hope, I did it the right way. I was not sure whether it was needed in Testumgebung or Testumgebung Ende-zu-Ende, so I just created a few pages in both. There should be 4 pages in Finnish: Willkomen -Beratung und Hillfe --Test Inhalte --Helferkreis

Nice, thank you. It is enough to make changes like this in Testumgebung. Works fine on web and android.

**Review by steffenkleinle — APPROVED** [review]
Tested on firefox and android. Had to uncomment lines 34 to 44 in `loadEvents.ts` and replace `events` with `[]` in line 45 and 46 though since events endpoint is currently not working, see https://chat.tuerantuer.org/digitalfabrik/pl/iq7n7jmizfb3pxzy5t53krnope.

Will app constans be translated as well?

**Comment by SteffiStuffel** [comment]
> Tested on firefox and android. Had to uncomment lines 34 to 44 in `loadEvents.ts` and replace `events` with `[]` in line 45 and 46 though since events endpoint is currently not working, see https://chat.tuerantuer.org/digitalfabrik/pl/iq7n7jmizfb3pxzy5t53krnope.
> 
> Will app constans be translated as well?

Anything I need to do here or is it fine to merge?

**Comment by steffenkleinle** [comment]
Fine to merge :) We can do it in a separate PR.

**Pull request merged**
