### PR TITLE
2618: Fix external link icon

### PR DESCRIPTION
**Pull request by steffenkleinle**
### Short description

Fix displaying of external link icon

### Proposed changes

Readd width and height for external link icon.

### Side effects

None.

### Resolved issues

Fixes: #2618.

---

### CODE REVIEW

**Comment by LeandraH** [comment]
@steffenkleinle I think there are a few extra commits in here :)

**Review by LeandraH — APPROVED** [review]
Thanks for the quick fix! Tested in Firefox (with refreshing the page this time 😬 )

**Review by f1sh1918 — APPROVED** [review]
tested on chrome

**Comment by ztefanie** [comment]
I do not see the icons?

**Comment by steffenkleinle** [comment]
> I do not see the icons?

@ztefanie the class name seems not to be set for those icons. Test on the page linked in the issue:
https://integreat.app/integreat-inhalte/de/ukraine/hilfe-fuer-die-ukraine

**Comment by ztefanie** [comment]
> > I do not see the icons?
> 
> @ztefanie the class name seems not to be set for those icons. Test on the page linked in the issue: https://integreat.app/integreat-inhalte/de/ukraine/hilfe-fuer-die-ukraine

oke. This page works as expected.

**Review by ztefanie — APPROVED** [review]

**Pull request merged**
