### PR TITLE
IGAPP-945: Iframe resizer

### PR DESCRIPTION
**Pull request by sarahsporck**
This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

There is still a lot that could be removed, but it would probably also mean to loose some functionality so keep that in mind.
Testable by starting the dev server and then opening the attached index.html
[index.zip](https://github.com/digitalfabrik/integreat-app/files/8381165/index.zip)

### CODE REVIEW

**Review by klinzo — COMMENTED** [review]
Nice work already. You just copied the `iframe.js` and removed some stuff, so no need to review this thoroughly right?

Am I doing something wrong? The height is always way to small for me while the width resizes correctly, see screenshot:
image

**Review by SteffiStuffel — COMMENTED** [review]
How can I test it?

**Comment by klinzo** [comment]
> How can I test it?

See description:
> There is still a lot that could be removed, but it would probably also mean to loose some functionality so keep that in mind.
Testable by starting the dev server and then opening the attached index.html
[index.zip](https://github.com/digitalfabrik/integreat-app/files/8381165/index.zip)

**Review by SteffiStuffel — APPROVED** [review]
Tested. Works fine also for height.
@klinzo height of parent div must also be set in css.

**Comment by klinzo** [comment]
> Tested. Works fine also for height. @klinzo height of parent div must also be set in css.

What do you mean/how do I do that?

**Comment by SteffiStuffel** [comment]
> > Tested. Works fine also for height. @klinzo height of parent div must also be set in css.
> 
> What do you mean/how do I do that?

e.g. this works: Just change the corresponding lines in the index.html.
```
    <div style="margin:20px; min-height: 600px;">
      <iframe src="http:/localhost:9000/testumgebung/de" width="50%" height="500pxpx" scrolling="no"></iframe>
    </div>
```

**Comment by f1sh1918** [comment]
Works fine. Just had to set
` <iframe src="http:/localhost:9000/testumgebung/de" width="100%" height="600px" scrolling="auto"></iframe>``
Just had to set `scrolling="auto"`for the news page

**Review by f1sh1918 — APPROVED** [review]

**Pull request merged**
