### PR TITLE
2597: Adjust feedback

### PR DESCRIPTION
**Pull request by steffenkleinle**
### Short description

Several small adjustments to the feedback.

### Proposed changes

- Remove the note instead of just hiding it
- Stop sending the actual query to the cms for search feedback
- Use our own loading spinner

### Side effects

Only the adjusted search term is sent to the CMS, the actual query is not sent anymore. This might lead to confusing feedback for the CMS users.

### Resolved issues

Fixes: #2597.

---

### CODE REVIEW

**Review by LeandraH — APPROVED** [review]
Nice! Tested in Firefox and emulated iOS

**Review by f1sh1918 — CHANGES_REQUESTED** [review]
When i go to search and type something and no result was found, the feedback form appears, but when i then delete the query which is mandatory. I can still can send the feedback which shouldn't be the case i think?

https://github.com/digitalfabrik/integreat-app/assets/37902063/efa8f77c-f43a-4376-921a-4f02f27e3df8

**Comment by steffenkleinle** [comment]
> When i go to search and type something and no result was found, the feedback form appears, but when i then delete the query which is mandatory. I can still can send the feedback which shouldn't be the case i think?

If the query is empty the search text is sent which is the same behavior as it is atm. If you think this should be changed please open a new issue. Personally I think that is okay.

**Review by f1sh1918 — APPROVED** [review]
Alright gonna open an issue. I think we should avoid the possibility to send empty feedback!

**Pull request merged**
