### PR TITLE
IGAPP-1039: Remove inappbrowser patch

### PR DESCRIPTION
**Pull request by steffenkleinle**
This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

### CODE REVIEW

**Review by SteffiStuffel — COMMENTED** [review]
I think you need to remove the patch file, also `native/patches/react-native-inappbrowser-reborn+3.6.3.patch`

https://github.com/digitalfabrik/integreat-app/pull/704/files#diff-3888309719de16c57954ea17c2b1a06d32c3807e05065c98e9cc7fc20feeaab3

**Review by SteffiStuffel — COMMENTED** [review]
Tested:

1) Query_all_packages is not in the manifest after building -> works fine


2) Opening external links is not working:  `[NotFoundError: The route https://www.github.com/digitalfabrik/integreat-app/ does not exist here.]`

Bildschirmfoto zu 2022-08-10 08-39-47

Not sure how to handle external links though, just added this one in cms.

**Comment by steffenkleinle** [comment]
>     2. Opening external links is not working:  `[NotFoundError: The route https://www.github.com/digitalfabrik/integreat-app/ does not exist here.]`

Where is this? It works fine for me for other external links.

**Comment by SteffiStuffel** [comment]
> > ```
> > 2. Opening external links is not working:  `[NotFoundError: The route https://www.github.com/digitalfabrik/integreat-app/ does not exist here.]`
> > ```
> 
> Where is this? It works fine for me for other external links.

Test cms -> Testumgebung -> Willkommen

**Review by f1sh1918 — COMMENTED** [review]
Tested on android emulator. neither can't open external links anymore. Weird that there is no issue yet for this on github repo ...

**Comment by steffenkleinle** [comment]
> Tested on android emulator. neither can't open external links anymore. Weird that there is no issue yet for this on github repo ...

Can you perhaps test on a real device as it is working fine for me? Maybe it is an issue with android emulator?

**Comment by SteffiStuffel** [comment]
Tested again with real devices, works fine.

**Comment by steffenkleinle** [comment]
@f1sh1918 @SteffiStuffel what to you want to do with this? I currently don't have time to investigate why it's not working on emulators anymore. Seems like this is the same issue: https://github.com/proyecto26/react-native-inappbrowser/issues/348

**Comment by SteffiStuffel** [comment]
> @f1sh1918 @SteffiStuffel what to you want to do with this? I currently don't have time to investigate why it's not working on emulators anymore. Seems like this is the same issue: [proyecto26/react-native-inappbrowser#348](https://github.com/proyecto26/react-native-inappbrowser/issues/348)

Either merge this and open a jira ticket with linking to the mentioned github issue, so we can fix this later / keep track of it
or close this PR, add a information to IGAPP-1039 and why it cannot be done currently. I prefer the first.

**Review by SteffiStuffel — APPROVED** [review]

**Pull request merged**
