### PR TITLE
2615: Set content direction in theme

### PR DESCRIPTION
**Pull request by LeandraH**
### Short description

This sets the content direction in the theme so we don't need to pass it around in props anymore.

I'll also create a second ticket for the stylelint rule Sarah suggested.

### Resolved issues

Fixes: #2615 

---

### CODE REVIEW

**Review by sarahsporck — APPROVED** [review]
Wow! This PR feel nice to review. Nicely done. Tested in firefox & safari.

**Review by steffenkleinle — COMMENTED** [review]
Nice, love it :heart_eyes: Can we do that for native as well? Or is that not possible for some reason?

**Comment by LeandraH** [comment]
> Nice, love it 😍 Can we do that for native as well? Or is that not possible for some reason?

We could but we don't pass around the direction in native via props since we already have the helper functions in `contentDirection.ts`. So I think it's not really necessary.

**Comment by steffenkleinle** [comment]
> > Nice, love it 😍 Can we do that for native as well? Or is that not possible for some reason?
> 
> We could but we don't pass around the direction in native via props since we already have the helper functions in `contentDirection.ts`. So I think it's not really necessary.

Hmm, while its true that it is easier to use than on web I think its still not as easy as having a prop in the theme since you still have to pass the language and use the helper function every time you want to access the content direction. The helper is still used 20+ times.

So I personally think it would be nicer to have that theme prop but you are completely right, it was much more important on web.

**Review by steffenkleinle — APPROVED** [review]

**Comment by LeandraH** [comment]
I think I'll leave it. It's already quite inconsistent between web and native because we don't just use the direction in native, we use all kinds of helper functions based on the direction. So even if we put all those helpers into the theme, it would be an inconsistent experience between native and web. I'd say we see if it becomes a problem in the future.

**Pull request merged**
