### PR TITLE
IGAPP-927: Add image alignment from cms

### PR DESCRIPTION
**Pull request by SteffiStuffel**
This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

See http://localhost:9000/testumgebung/de/bilder

### CODE REVIEW

**Review by Taggotty — APPROVED** [review]
Tested on Firefox. 
Really impressed by your advanced css knowloedge here, Steffi. Can't wait for you're introduction in css, later this year :D

**Review by klinzo — APPROVED** [review]
Looking good on firefox. In native apps it looks a little bit weird, do you think we can do something there as well?
https://integreat.app/testumgebung/de/bilder

**Comment by SteffiStuffel** [comment]
> Looking good on firefox. In native apps it looks a little bit weird, do you think we can do something there as well? https://integreat.app/testumgebung/de/bilder

Not sure what you mean. When having a browser open on a native device or in the native app?

**Comment by klinzo** [comment]
> > Looking good on firefox. In native apps it looks a little bit weird, do you think we can do something there as well? https://integreat.app/testumgebung/de/bilder
> 
> Not sure what you mean. When having a browser open on a native device or in the native app?

I meant in the native app.

**Comment by SteffiStuffel** [comment]
> > > Looking good on firefox. In native apps it looks a little bit weird, do you think we can do something there as well? https://integreat.app/testumgebung/de/bilder
> > 
> > 
> > Not sure what you mean. When having a browser open on a native device or in the native app?
> 
> I meant in the native app.

Can you open a ticket, if you (still) think we should also do this for native?

**Comment by klinzo** [comment]
https://issues.tuerantuer.org/browse/IGAPP-975

**Pull request merged**
