### PR TITLE
IGAPP-1286: Fix text alignment of local news

### PR DESCRIPTION
**Pull request by steffenkleinle**
This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

### CODE REVIEW

**Review by LeandraH — COMMENTED** [review]
It hasn't been fixed in this one single push notification in Arabic in Testumgebung, but maybe that's because of the Latin letters in there?

image

**Comment by steffenkleinle** [comment]
> > It hasn't been fixed in this one single push notification in Arabic in Testumgebung, but maybe that's because of the Latin letters in there?
> Hmmm, in theory LTR and RTL chars should be counted and the direction with more chars wins. So not sure what is happening here.

I just tested it and I can't reproduce it, are you sure you checked out the right branch? For me its right aligned.

**Review by LeandraH — APPROVED** [review]
You're right, sorry about that, must have gotten confused about the branches

**Review by f1sh1918 — APPROVED** [review]
Works fine on android

**Pull request merged**
